export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'

export const FETCH_TODOS_START = 'FETCH_TODOS_START'
export const FETCH_TODOS_FAIL = 'FETCH_TODOS_FAIL'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'

export const FETCH_POSTS_START = 'FETCH_POSTS_START'
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'

export const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START'
export const FETCH_PHOTOS_FAIL = 'FETCH_PHOTOS_FAIL'
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS'